// CONSTANTES PARA NOMBRES DE TABLAS Y OPERACIONES PARA GUARDADO DE LOGS DE BASES DE DATOS (TRANSACCIONES)
module.exports = {
    //OPERATION DATABASE
    OPERATION_INSERT: 'INSERT',
    OPERATION_UPDATE: 'UPDATE',
    OPERATION_DELETE: 'DELETE',

    //TABLES DATABASE
    SECURITY_USER: 'security.user'
}

